<?php

/**
 * @file
 * Contains example_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
// function example_module_help($route_name, RouteMatchInterface $route_match)
// {
//   switch ($route_name) {
//       // Main module help for the example_module module.
//     case 'help.page.example_module':
//       $output = '';
//       $output .= '<h3>' . t('About') . '</h3>';
//       $output .= '<p>' . t('Example module') . '</p>';
//       return $output;

//     default:
//   }
// }


function example_module_theme($existing, $type, $theme, $path)
{
  $items = [];
  $items['example_module_form'] = [
    'render element' => 'form',
    'template' => 'example-form',
    'path' => $path . '/templates'
  ];

  return $items;
}

function example_module_form_alter(&$form, $form_state, $form_id)
{
  if ($form_id === 'example_module_form') {
    $form['#attached']['library'][] = 'example_module/bootstrap';
    // $form['#theme'] = ['example_module_form'];
  }
}
